# Ejercicios Modulo 5. Librerías especializadas en datos (Soluciones)

Consideraciones a tener en cuenta: 

* Guardar este documento con el siguiente formato para su entrega: __M5_05_nombre_apellido1_apellido2__
* Realizar los ejercicios con las herramientas vistas en las sesiones. 
* Comentar el código
* Utilizar nombres de variables apropiados, si vais a guardar una nota, llamar a esa variable nota, no n o x

**1) Trabajemos con NumPy**

* Importa numpy y usa un alias para poder utilizar sus recursos
* Crea un array de elementos (del 10 al 100)
* Invertir el array
* Crear un array 3x3 con valores de 0 a 8
* Crear un array identidad de 6x6
* Crear un array con valores al azar con forma 3x3x3
* Crear dos arrays con valores al azar A y B, verificar si son iguales (hay varias opciones, investigar)

In [1]:
# Completa el ejercicio aquí
import numpy as np

# Crear un array de elementos (del 10 al 100)
array_1 = np.arange(10, 101)
print("Array original:")
print(array_1)

# Invertir el array
inverted_array = np.flip(array_1)
print("Array invertido:")
print(inverted_array)

# Crear un array 3x3 con valores de 0 a 8
array_2 = np.arange(9).reshape(3, 3)
print("Array 3x3:")
print(array_2)

# Crear un array identidad de 6x6
identity_array = np.eye(6)
print("Array identidad 6x6:")
print(identity_array)

# Crear un array con valores al azar con forma 3x3x3
random_array = np.random.rand(3, 3, 3)
print("Array al azar 3x3x3:")
print(random_array)

# Crear dos arrays con valores al azar A y B, verificar si son iguales
array_A = np.random.rand(3, 3)
array_B = np.random.rand(3, 3)

# Opción 1: Comparar elemento por elemento y ver si son iguales
are_equal = np.array_equal(array_A, array_B)
print("¿Los arrays A y B son iguales? (Opción 1):", are_equal)

# Opción 2: Verificar si los arrays tienen la misma forma y todos sus elementos son iguales
are_equal_all = np.allclose(array_A, array_B)
print("¿Los arrays A y B son iguales? (Opción 2):", are_equal_all)



Array original:
[ 10  11  12  13  14  15  16  17  18  19  20  21  22  23  24  25  26  27
  28  29  30  31  32  33  34  35  36  37  38  39  40  41  42  43  44  45
  46  47  48  49  50  51  52  53  54  55  56  57  58  59  60  61  62  63
  64  65  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80  81
  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99
 100]
Array invertido:
[100  99  98  97  96  95  94  93  92  91  90  89  88  87  86  85  84  83
  82  81  80  79  78  77  76  75  74  73  72  71  70  69  68  67  66  65
  64  63  62  61  60  59  58  57  56  55  54  53  52  51  50  49  48  47
  46  45  44  43  42  41  40  39  38  37  36  35  34  33  32  31  30  29
  28  27  26  25  24  23  22  21  20  19  18  17  16  15  14  13  12  11
  10]
Array 3x3:
[[0 1 2]
 [3 4 5]
 [6 7 8]]
Array identidad 6x6:
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]
Array al azar 3x3x3:
[[[0.11148701 0.8

**2) Sigamos con NumPy**

* Crear un array de 100 elementos aleatorios comprendidos entre 1 y 1000 (pueden ser números enteros).
* Este array se llamara dólares
* Crear otro array llamado euros
* Realizar la conversión de los precios en dólares del primer array al segundo array en euros. Se puede serguir la siguiente conversión:
    - 1 EUR = 1,14362 USD
    - 1 USD = 0,874413 EUR
* Mostrar el resultado del array de euros pero redondeado a 2 decimales

In [2]:
# Completa el ejercicio aquí
import numpy as np

# Crear un array de 100 elementos aleatorios entre 1 y 1000
dolares = np.random.randint(1, 1001, 100)
print("Array en dólares:")
print(dolares)

# Definir el factor de conversión de dólares a euros
conversion_dolar_euro = 0.874413

# Crear el array de euros mediante la conversión
euros = dolares * conversion_dolar_euro
print("Array en euros:")
print(euros)

# Redondear el array de euros a 2 decimales
euros_redondeados = np.round(euros, 2)
print("Array en euros redondeado a 2 decimales:")
print(euros_redondeados)


Array en dólares:
[106  55 147 317 777  39 686 157 952 731 816 571 164 801 647  59 798  74
 910 856 604 783 601 570 256 386 679 666 340 926 856 757  24  55 670 359
  17 270 248 342 865 147 761 804 864 776 770 391 859 867 852 577 867 451
 566 685 626 400 602 666 759 497 134  24 376 833 757 775 335 525 594 784
 316 177 672 976 669 658 178 662 872 227 483 870 457 389 106 304 484 404
 841 434 373 315 333 903 513 266 151 353]
Array en euros:
[ 92.687778  48.092715 128.538711 277.188921 679.418901  34.102107
 599.847318 137.282841 832.441176 639.195903 713.521008 499.289823
 143.403732 700.404813 565.745211  51.590367 697.781574  64.706562
 795.71583  748.497528 528.145452 684.665379 525.522213 498.41541
 223.849728 337.523418 593.726427 582.359058 297.30042  809.706438
 748.497528 661.930641  20.985912  48.092715 585.85671  313.914267
  14.865021 236.09151  216.854424 299.049246 756.367245 128.538711
 665.428293 703.028052 755.492832 678.544488 673.29801  341.895483
 751.120767 758.116071 7

**3) Trabajemos con pandas**

* Importa pandas y usa un alias para poder utilizar sus recursos
* Cargar como dataframe de pandas el csv 05_05_imdb_titulos.csv y mostrar sus 5 primeros registros
* Cargar como dataframe de pandas el csv 05_05_imdb_elenco.csv y mostrar sus 5 primeros registros
* Mostrar el número de registros del dataframe de titulos
* Mostrar el número de registros del dataframe de elenco
* Mostrar las 5 peliculas más antiguas del listado de titulos
* Mostrar las peliculas que en el titulo tienen la palabra "Dracula". También mostrar el número total de peliculas que coincidan con este requisito
* Mostrar los 10 titulos más comunes (que más se repiten)
* Mostrar cual fue la primer pelicula hecha titulada "Romeo and Juliet" 
* Listar todas las peliculas que contengan la palabra "Exorcist" ordenadas de la más vieja a la más reciente
* Mostrar cuantas peliculas fueron hechas en el año 1950
* Mostrar cuantas peliculas fueron hechas de 1950 a 1959
* Mostrar todos los roles o papeles que hubo en la pelicula "The Godfather". También mostrar el número total de coincidencias
* Mostrar el elenco completo ordenado por la clasificacion "n" de la pelicula "Dracula" de 1958
* Mostrar cuantos papeles de "Bruce Wayne" han sido hechos en la historia de las peliculas
* Mostrar cuantos papeles ha hecho "Robert De Niro" en su carrera
* Listado de papeles como protagonista (n=1) que tuvo el actor "Charlton Heston" en la década de los 60's, ordenado por año de forma descendente
* Mostrar cuantos papeles para actores hubo en la década de los 50's
* Mostrar cuantos papeles para actrices hubo en la década de los 50's

In [6]:
# Completa el ejercicio aquí
import pandas as pd

# Cargar el csv 05_05_imdb_titulos.csv como dataframe y mostrar sus 5 primeros registros
df_titulos = pd.read_csv('05_05_imdb_titulos.csv')
print("Dataframe de títulos - 5 primeros registros:")
print(df_titulos.head())

# Cargar el csv 05_05_imdb_elenco.csv como dataframe y mostrar sus 5 primeros registros
df_elenco = pd.read_csv('05_05_imdb_elenco.csv')
print("\nDataframe de elenco - 5 primeros registros:")
print(df_elenco.head())

# Mostrar el número de registros del dataframe de títulos
num_registros_titulos = df_titulos.shape[0]
print("\nNúmero de registros en el dataframe de títulos:", num_registros_titulos)

# Mostrar el número de registros del dataframe de elenco
num_registros_elenco = df_elenco.shape[0]
print("Número de registros en el dataframe de elenco:", num_registros_elenco)

# Mostrar las 5 películas más antiguas del listado de títulos
print("\nLas 5 películas más antiguas:")
print(df_titulos.nsmallest(5, 'year'))

# Mostrar las películas que en el título tienen la palabra "Dracula"
df_dracula = df_titulos[df_titulos['title'].str.contains('Dracula', case=False) & df_titulos['title'].notna()]
num_peliculas_dracula = df_dracula.shape[0]
print("\nPelículas que contienen la palabra 'Dracula':")
print(df_dracula)
print("\nNúmero total de películas que contienen la palabra 'Dracula':", num_peliculas_dracula)

# Mostrar los 10 títulos más comunes (que más se repiten)
print("\nLos 10 títulos más comunes:")
print(df_titulos['title'].value_counts().nlargest(10))

# Mostrar cuál fue la primera película hecha titulada "Romeo and Juliet"
primera_pelicula_romeo_juliet = df_titulos[df_titulos['title'] == 'Romeo and Juliet'].nsmallest(1, 'year')
print("\nPrimera película titulada 'Romeo and Juliet':")
print(primera_pelicula_romeo_juliet)

# Listar todas las películas que contengan la palabra "Exorcist" ordenadas de la más vieja a la más reciente
print("\nPelículas que contienen la palabra 'Exorcist', ordenadas de la más vieja a la más reciente:")
df_exorcist = df_titulos[df_titulos['title'].str.contains('Exorcist', case=False)& df_titulos['title'].notna()].sort_values('year') 
print(df_exorcist)

# Mostrar cuántas películas fueron hechas en el año 1950
num_peliculas_1950 = df_titulos[df_titulos['year'] == 1950].shape[0]
print("\nNúmero de películas hechas en el año 1950:", num_peliculas_1950)

# Mostrar cuántas películas fueron hechas de 1950 a 1959
num_peliculas_1950_1959 = df_titulos[df_titulos['year'].between(1950, 1959)].shape[0]
print("Número de películas hechas de 1950 a 1959:", num_peliculas_1950_1959)

# Mostrar todos los roles o papeles que hubo en la película "The Godfather"
roles_godfather = df_elenco[df_elenco['title'] == 'The Godfather']['character']
num_roles_godfather = roles_godfather.shape[0]
print("\nRoles en la película 'The Godfather':")
print(roles_godfather)
print("Número total de roles en la película 'The Godfather':", num_roles_godfather)

# Mostrar el elenco completo ordenado por la clasificación "n" de la película "Dracula" de 1958
elenco_dracula_1958 = df_elenco[(df_elenco['title'] == 'Dracula') & (df_elenco['year'] == 1958)].sort_values('n')
print("\nElenco completo de la película 'Dracula' de 1958, ordenado por clasificación 'n':")
print(elenco_dracula_1958)

# Mostrar cuántos papeles de "Bruce Wayne" han sido hechos en la historia de las películas
num_papeles_bruce_wayne = df_elenco[df_elenco['name'] == 'Bruce Wayne'].shape[0]
print("\nNúmero de papeles hechos por 'Bruce Wayne':", num_papeles_bruce_wayne)

# Mostrar cuántos papeles ha hecho "Robert De Niro" en su carrera
num_papeles_robert_de_niro = df_elenco[df_elenco['name'] == 'Robert De Niro'].shape[0]
print("Número de papeles hechos por 'Robert De Niro':", num_papeles_robert_de_niro)

# Listado de papeles como protagonista (n=1) que tuvo el actor "Charlton Heston" en la década de los 60's, ordenado por año de forma descendente
papeles_charlton_heston_60s = df_elenco[(df_elenco['name'] == 'Charlton Heston') & (df_elenco['n'] == 1) & (df_elenco['year'].between(1960, 1969))].sort_values('year', ascending=False)
print("\nPapeles como protagonista de Charlton Heston en los 60's, ordenados por año (descendente):")
print(papeles_charlton_heston_60s)

# Mostrar cuántos papeles para actores hubo en la década de los 50's
num_papeles_actores_50s = df_elenco[(df_elenco['type'] == 'actor') & (df_elenco['year'].between(1950, 1959))].shape[0]
print("\nNúmero de papeles para actores en los 50's:", num_papeles_actores_50s)

# Mostrar cuántos papeles para actrices hubo en la década de los 50's
num_papeles_actrices_50s = df_elenco[(df_elenco['type'] == 'actress') & (df_elenco['year'].between(1950, 1959))].shape[0]
print("Número de papeles para actrices en los 50's:", num_papeles_actrices_50s)


Dataframe de títulos - 5 primeros registros:
                                   title  year
0                                 Mahler  1974
1           Ogon, voda i... mednye truby  1968
2  Ana Nojoom bent alasherah wamotalagah  2014
3                      Malu de Bicicleta  2010
4             Nazareno Apostol: Boy Ahas  1989

Dataframe de elenco - 5 primeros registros:
                  title  year      name   type                character     n
0        Closet Monster  2015  Buffy #1  actor                  Buffy 4  31.0
1       Suuri illusioni  1985    Homo $  actor                   Guests  22.0
2   Battle of the Sexes  2017   $hutter  actor          Bobby Riggs Fan  10.0
3  Secret in Their Eyes  2015   $hutter  actor          2002 Dodger Fan   NaN
4            Steve Jobs  2015   $hutter  actor  1988 Opera House Patron   NaN

Número de registros en el dataframe de títulos: 230407
Número de registros en el dataframe de elenco: 3564650

Las 5 películas más antiguas:
                  